/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Input_Pesanan_c;
import Controller.Kostumer_c;
import Controller.Pemasukan_c;
import Controller.Pengeluaran_c;
import Controller.Produk_c;
import Models.input_pesanan_m;
import Models.kostumer_m;
import Models.pemasukan_m;
import Models.pengeluaran_m;
import Models.produk_m;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author baiha
 */
public class info_menu extends javax.swing.JFrame {

    /**
     * Creates new form info_menu
     */
    public info_menu() {
        setIcon();
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTabel = new javax.swing.JPanel();
        logo1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        bttnproduk1 = new javax.swing.JButton();
        btnpesanan1 = new javax.swing.JButton();
        btnkostumer1 = new javax.swing.JButton();
        btninfo = new javax.swing.JButton();
        btnpemasukan = new javax.swing.JButton();
        btnpengeluaran = new javax.swing.JButton();
        baground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ToothSome");

        panelTabel.setBackground(new java.awt.Color(102, 102, 102));

        logo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profil_photo.png"))); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Database Name:toothsome\nPort Database: 3306\nContact Depeloper: @randagiya\nJar: mysql-connector-java-8.0.29, jcalendar-1.4");
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout panelTabelLayout = new javax.swing.GroupLayout(panelTabel);
        panelTabel.setLayout(panelTabelLayout);
        panelTabelLayout.setHorizontalGroup(
            panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelLayout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(logo1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addGap(285, 285, 285))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addGap(37, 37, 37))
        );
        panelTabelLayout.setVerticalGroup(
            panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(160, 354));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profil_photo.png"))); // NOI18N

        bttnproduk1.setBackground(new java.awt.Color(0, 0, 0));
        bttnproduk1.setFont(new java.awt.Font("Bodoni MT", 1, 15)); // NOI18N
        bttnproduk1.setForeground(new java.awt.Color(255, 255, 255));
        bttnproduk1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bread.png"))); // NOI18N
        bttnproduk1.setText("Produk");
        bttnproduk1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttnproduk1.setPreferredSize(new java.awt.Dimension(137, 33));
        bttnproduk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnproduk1ActionPerformed(evt);
            }
        });

        btnpesanan1.setBackground(new java.awt.Color(0, 0, 0));
        btnpesanan1.setFont(new java.awt.Font("Bodoni MT", 1, 15)); // NOI18N
        btnpesanan1.setForeground(new java.awt.Color(255, 255, 255));
        btnpesanan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/to-do-list.png"))); // NOI18N
        btnpesanan1.setText("Pesanan");
        btnpesanan1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnpesanan1.setPreferredSize(new java.awt.Dimension(137, 33));
        btnpesanan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpesanan1MouseClicked(evt);
            }
        });
        btnpesanan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesanan1ActionPerformed(evt);
            }
        });

        btnkostumer1.setBackground(new java.awt.Color(0, 0, 0));
        btnkostumer1.setFont(new java.awt.Font("Bodoni MT", 1, 15)); // NOI18N
        btnkostumer1.setForeground(new java.awt.Color(255, 255, 255));
        btnkostumer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/team.png"))); // NOI18N
        btnkostumer1.setText("Kostumer");
        btnkostumer1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnkostumer1.setPreferredSize(new java.awt.Dimension(137, 33));
        btnkostumer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkostumer1ActionPerformed(evt);
            }
        });

        btninfo.setBackground(new java.awt.Color(0, 0, 0));
        btninfo.setFont(new java.awt.Font("Bodoni MT", 1, 15)); // NOI18N
        btninfo.setForeground(java.awt.Color.lightGray);
        btninfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/info.png"))); // NOI18N
        btninfo.setText("Info");
        btninfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btninfo.setPreferredSize(new java.awt.Dimension(137, 33));
        btninfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninfoActionPerformed(evt);
            }
        });

        btnpemasukan.setBackground(new java.awt.Color(0, 0, 0));
        btnpemasukan.setFont(new java.awt.Font("Bodoni MT", 1, 15)); // NOI18N
        btnpemasukan.setForeground(new java.awt.Color(255, 255, 255));
        btnpemasukan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/financial-profit.png"))); // NOI18N
        btnpemasukan.setText("Pemasukan");
        btnpemasukan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnpemasukan.setMaximumSize(new java.awt.Dimension(137, 33));
        btnpemasukan.setMinimumSize(new java.awt.Dimension(137, 33));
        btnpemasukan.setPreferredSize(new java.awt.Dimension(137, 33));
        btnpemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpemasukanActionPerformed(evt);
            }
        });

        btnpengeluaran.setBackground(new java.awt.Color(0, 0, 0));
        btnpengeluaran.setFont(new java.awt.Font("Bodoni MT", 1, 15)); // NOI18N
        btnpengeluaran.setForeground(new java.awt.Color(255, 255, 255));
        btnpengeluaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/money.png"))); // NOI18N
        btnpengeluaran.setText("Pengeluaran");
        btnpengeluaran.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnpengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpengeluaranActionPerformed(evt);
            }
        });

        baground.setBackground(new java.awt.Color(153, 255, 255));
        baground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pexels-marta-dzedyshko-7693950.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttnproduk1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkostumer1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btninfo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpesanan1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(baground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(bttnproduk1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(btnpesanan1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(btninfo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(btnkostumer1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(btnpemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(btnpengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(baground, javax.swing.GroupLayout.PREFERRED_SIZE, 800, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(panelTabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(panelTabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnproduk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnproduk1ActionPerformed
        // TODO add your handling code here:
        produk_m model = new produk_m();
        produk_menu view2 = new produk_menu();
        produk view = new produk();
        Produk_c pro_c = new Produk_c(view2, model, view);

        pro_c.tampil_data();
        view2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttnproduk1ActionPerformed

    private void btnpesanan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpesanan1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpesanan1MouseClicked

    private void btnpesanan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesanan1ActionPerformed
        input_pesanan_m model = new input_pesanan_m();
        input_pesanan view = new input_pesanan();
        Input_Pesanan_c ctrl = new Input_Pesanan_c(view, model);

        ctrl.tampil_data();
        view.setVisible(true);
    }//GEN-LAST:event_btnpesanan1ActionPerformed

    private void btnkostumer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkostumer1ActionPerformed
        // TODO add your handling code here:
        kostumer_m model = new kostumer_m();
        kostumer_menu view2 = new kostumer_menu();
        kostumer view = new kostumer();
        Kostumer_c ctrl = new Kostumer_c(view, model, view2);

        view2.setVisible(true);
        ctrl.tampil_data();
        this.dispose();
    }//GEN-LAST:event_btnkostumer1ActionPerformed

    private void btninfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btninfoActionPerformed

    private void btnpemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpemasukanActionPerformed
        // TODO add your handling code here:
        pemasukan_m model = new pemasukan_m();
        pemasukan_menu view2 = new pemasukan_menu();
        pemasukan view = new pemasukan();
        Pemasukan_c ctrl = new Pemasukan_c(view, view2, model);

        ctrl.tampil_data();
        view2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnpemasukanActionPerformed

    private void btnpengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpengeluaranActionPerformed
        // TODO add your handling code here:
        pengeluaran_m model = new pengeluaran_m();
        pengeluaran_menu view2 = new pengeluaran_menu();
        pengeluaran_fix view = new pengeluaran_fix();
        Pengeluaran_c ctrl = new Pengeluaran_c(view, view2, model);

        ctrl.tampil_data();
        view2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnpengeluaranActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel baground;
    public javax.swing.JButton btninfo;
    public javax.swing.JButton btnkostumer1;
    public javax.swing.JButton btnpemasukan;
    public javax.swing.JButton btnpengeluaran;
    public javax.swing.JButton btnpesanan1;
    public javax.swing.JButton bttnproduk1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo1;
    private javax.swing.JPanel panelTabel;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("bread.png")));
    }
}
