/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Input_Pesanan_c;
import Controller.Kostumer_c;
import Controller.Pemasukan_c;
import Controller.Pengeluaran_c;
import Controller.Produk_c;
import Models.input_pesanan_m;
import Models.kostumer_m;
import Models.pemasukan_m;
import Models.pengeluaran_m;
import Models.produk_m;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author baiha
 */
public class produk_menu extends javax.swing.JFrame {

    /**
     * Creates new form produk_menu
     */
    public produk_menu() {
        setIcon();
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        MenubtnProduk = new javax.swing.JButton();
        btnpesanan1 = new javax.swing.JButton();
        btnkostumer1 = new javax.swing.JButton();
        btninfo = new javax.swing.JButton();
        btnpemasukan = new javax.swing.JButton();
        btnpengeluaran = new javax.swing.JButton();
        baground = new javax.swing.JLabel();
        panelTabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        panelPembukuan = new javax.swing.JPanel();
        btnCetak = new javax.swing.JButton();
        panelDetail = new javax.swing.JPanel();
        detailbtn = new javax.swing.JButton();
        panelInput = new javax.swing.JPanel();
        btninputpesanan = new javax.swing.JButton();
        panelKalkulator = new javax.swing.JPanel();
        btnkalkulator = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ToothSome");

        jPanel2.setPreferredSize(new java.awt.Dimension(160, 354));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profil_photo.png"))); // NOI18N

        MenubtnProduk.setBackground(new java.awt.Color(0, 0, 0));
        MenubtnProduk.setFont(new java.awt.Font("Bodoni MT", 1, 15)); // NOI18N
        MenubtnProduk.setForeground(java.awt.Color.lightGray);
        MenubtnProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bread.png"))); // NOI18N
        MenubtnProduk.setText("Produk");
        MenubtnProduk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MenubtnProduk.setPreferredSize(new java.awt.Dimension(137, 33));
        MenubtnProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenubtnProdukActionPerformed(evt);
            }
        });

        btnpesanan1.setBackground(new java.awt.Color(0, 0, 0));
        btnpesanan1.setFont(new java.awt.Font("Bodoni MT", 1, 15)); // NOI18N
        btnpesanan1.setForeground(new java.awt.Color(255, 255, 255));
        btnpesanan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/to-do-list.png"))); // NOI18N
        btnpesanan1.setText("Pesanan");
        btnpesanan1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnpesanan1.setPreferredSize(new java.awt.Dimension(137, 33));
        btnpesanan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpesanan1MouseClicked(evt);
            }
        });
        btnpesanan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesanan1ActionPerformed(evt);
            }
        });

        btnkostumer1.setBackground(new java.awt.Color(0, 0, 0));
        btnkostumer1.setFont(new java.awt.Font("Bodoni MT", 1, 15)); // NOI18N
        btnkostumer1.setForeground(new java.awt.Color(255, 255, 255));
        btnkostumer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/team.png"))); // NOI18N
        btnkostumer1.setText("Kostumer");
        btnkostumer1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnkostumer1.setPreferredSize(new java.awt.Dimension(137, 33));
        btnkostumer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkostumer1ActionPerformed(evt);
            }
        });

        btninfo.setBackground(new java.awt.Color(0, 0, 0));
        btninfo.setFont(new java.awt.Font("Bodoni MT", 1, 15)); // NOI18N
        btninfo.setForeground(new java.awt.Color(255, 255, 255));
        btninfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/info.png"))); // NOI18N
        btninfo.setText("Info");
        btninfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btninfo.setPreferredSize(new java.awt.Dimension(137, 33));
        btninfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninfoActionPerformed(evt);
            }
        });

        btnpemasukan.setBackground(new java.awt.Color(0, 0, 0));
        btnpemasukan.setFont(new java.awt.Font("Bodoni MT", 1, 15)); // NOI18N
        btnpemasukan.setForeground(new java.awt.Color(255, 255, 255));
        btnpemasukan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/financial-profit.png"))); // NOI18N
        btnpemasukan.setText("Pemasukan");
        btnpemasukan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnpemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpemasukanActionPerformed(evt);
            }
        });

        btnpengeluaran.setBackground(new java.awt.Color(0, 0, 0));
        btnpengeluaran.setFont(new java.awt.Font("Bodoni MT", 1, 15)); // NOI18N
        btnpengeluaran.setForeground(new java.awt.Color(255, 255, 255));
        btnpengeluaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/money.png"))); // NOI18N
        btnpengeluaran.setText("Pengeluaran");
        btnpengeluaran.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnpengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpengeluaranActionPerformed(evt);
            }
        });

        baground.setBackground(new java.awt.Color(153, 255, 255));
        baground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pexels-marta-dzedyshko-7693950.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MenubtnProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkostumer1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btninfo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpesanan1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(baground, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(MenubtnProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(btnpesanan1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(btninfo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(btnkostumer1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(btnpemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(btnpengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(baground, javax.swing.GroupLayout.PREFERRED_SIZE, 800, Short.MAX_VALUE)
        );

        panelTabel.setBackground(new java.awt.Color(102, 102, 102));
        panelTabel.setPreferredSize(new java.awt.Dimension(710, 647));

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Produk", "Nama Produk", "Jumlah", "Harga", "Tanggal/Bulan/Tahun"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table2.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table2);

        panelPembukuan.setBackground(new java.awt.Color(255, 102, 153));
        panelPembukuan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        btnCetak.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        btnCetak.setForeground(new java.awt.Color(255, 255, 255));
        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-storage.png"))); // NOI18N
        btnCetak.setText("Pembukuan");
        btnCetak.setContentAreaFilled(false);
        btnCetak.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout panelPembukuanLayout = new javax.swing.GroupLayout(panelPembukuan);
        panelPembukuan.setLayout(panelPembukuanLayout);
        panelPembukuanLayout.setHorizontalGroup(
            panelPembukuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelPembukuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnCetak, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
        );
        panelPembukuanLayout.setVerticalGroup(
            panelPembukuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
            .addGroup(panelPembukuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnCetak, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
        );

        panelDetail.setBackground(new java.awt.Color(255, 153, 153));
        panelDetail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        detailbtn.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        detailbtn.setForeground(new java.awt.Color(255, 255, 255));
        detailbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        detailbtn.setText("Detail");
        detailbtn.setContentAreaFilled(false);
        detailbtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        detailbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDetailLayout = new javax.swing.GroupLayout(panelDetail);
        panelDetail.setLayout(panelDetailLayout);
        panelDetailLayout.setHorizontalGroup(
            panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
            .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(detailbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
        );
        panelDetailLayout.setVerticalGroup(
            panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
            .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(detailbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
        );

        panelInput.setBackground(new java.awt.Color(51, 153, 255));
        panelInput.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        btninputpesanan.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        btninputpesanan.setForeground(new java.awt.Color(255, 255, 255));
        btninputpesanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/input.png"))); // NOI18N
        btninputpesanan.setText("Input Pesanan");
        btninputpesanan.setContentAreaFilled(false);
        btninputpesanan.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btninputpesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninputpesananActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInputLayout = new javax.swing.GroupLayout(panelInput);
        panelInput.setLayout(panelInputLayout);
        panelInputLayout.setHorizontalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInputLayout.createSequentialGroup()
                    .addComponent(btninputpesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 177, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelInputLayout.setVerticalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
            .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btninputpesanan, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
        );

        panelKalkulator.setBackground(new java.awt.Color(0, 153, 153));
        panelKalkulator.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        btnkalkulator.setBackground(new java.awt.Color(153, 0, 153));
        btnkalkulator.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        btnkalkulator.setForeground(new java.awt.Color(255, 255, 255));
        btnkalkulator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calculator.png"))); // NOI18N
        btnkalkulator.setText("Kalkulator");
        btnkalkulator.setContentAreaFilled(false);
        btnkalkulator.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnkalkulator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkalkulatorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelKalkulatorLayout = new javax.swing.GroupLayout(panelKalkulator);
        panelKalkulator.setLayout(panelKalkulatorLayout);
        panelKalkulatorLayout.setHorizontalGroup(
            panelKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKalkulatorLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnkalkulator, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
        );
        panelKalkulatorLayout.setVerticalGroup(
            panelKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnkalkulator, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelTabelLayout = new javax.swing.GroupLayout(panelTabel);
        panelTabel.setLayout(panelTabelLayout);
        panelTabelLayout.setHorizontalGroup(
            panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPembukuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelKalkulator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
            .addGroup(panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabelLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                    .addGap(22, 22, 22)))
        );
        panelTabelLayout.setVerticalGroup(
            panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPembukuan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelKalkulator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(580, Short.MAX_VALUE))
            .addGroup(panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTabelLayout.createSequentialGroup()
                    .addGap(231, 231, 231)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addGap(19, 19, 19)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(663, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(panelTabel, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(panelTabel, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void detailbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailbtnActionPerformed

        produk_m pro_m = new produk_m();
        produk_menu view2 = new produk_menu();
        produk view = new produk();
        Produk_c ctrl = new Produk_c(view2, pro_m, view);

        ctrl.KosongFromProduk();
        ctrl.tampil_data();
        ctrl.ambil_id();

        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_detailbtnActionPerformed

    private void btninputpesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninputpesananActionPerformed
        // TODO add your handling code here:
        input_pesanan_m model = new input_pesanan_m();
        input_pesanan view = new input_pesanan();
        Input_Pesanan_c ctrl = new Input_Pesanan_c(view, model);

        ctrl.tampil_data();
        view.setVisible(true);
    }//GEN-LAST:event_btninputpesananActionPerformed

    private void btnkalkulatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkalkulatorActionPerformed
        // TODO add your handling code here:
        calculator cal = new calculator();
        cal.setVisible(true);
    }//GEN-LAST:event_btnkalkulatorActionPerformed

    private void MenubtnProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenubtnProdukActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MenubtnProdukActionPerformed

    private void btnpesanan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpesanan1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpesanan1MouseClicked

    private void btnpesanan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesanan1ActionPerformed
        input_pesanan_m model = new input_pesanan_m();
        input_pesanan view = new input_pesanan();
        Input_Pesanan_c ctrl = new Input_Pesanan_c(view, model);

        ctrl.tampil_data();
        view.setVisible(true);
    }//GEN-LAST:event_btnpesanan1ActionPerformed

    private void btninfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninfoActionPerformed
        // TODO add your handling code here:
        info_menu info = new info_menu();
        info.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btninfoActionPerformed

    private void btnpemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpemasukanActionPerformed
        // TODO add your handling code here:
        pemasukan_m model = new pemasukan_m();
        pemasukan_menu view2 = new pemasukan_menu();
        pemasukan view = new pemasukan();
        Pemasukan_c ctrl = new Pemasukan_c(view, view2, model);

        ctrl.tampil_data();
        view2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnpemasukanActionPerformed

    private void btnpengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpengeluaranActionPerformed
        // TODO add your handling code here:
        pengeluaran_m model = new pengeluaran_m();
        pengeluaran_menu view2 = new pengeluaran_menu();
        pengeluaran_fix view = new pengeluaran_fix();
        Pengeluaran_c ctrl = new Pengeluaran_c(view, view2, model);

        ctrl.tampil_data();
        view2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnpengeluaranActionPerformed

    private void btnkostumer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkostumer1ActionPerformed
        // TODO add your handling code here:
        kostumer_m model = new kostumer_m();
        kostumer_menu view2 = new kostumer_menu();
        kostumer view = new kostumer();
        Kostumer_c ctrl = new Kostumer_c(view, model, view2);

        view2.setVisible(true);
        ctrl.tampil_data();
        this.dispose();

    }//GEN-LAST:event_btnkostumer1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton MenubtnProduk;
    private javax.swing.JLabel baground;
    public javax.swing.JButton btnCetak;
    public javax.swing.JButton btninfo;
    private javax.swing.JButton btninputpesanan;
    private javax.swing.JButton btnkalkulator;
    public javax.swing.JButton btnkostumer1;
    public javax.swing.JButton btnpemasukan;
    public javax.swing.JButton btnpengeluaran;
    public javax.swing.JButton btnpesanan1;
    private javax.swing.JButton detailbtn;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panelDetail;
    private javax.swing.JPanel panelInput;
    private javax.swing.JPanel panelKalkulator;
    private javax.swing.JPanel panelPembukuan;
    private javax.swing.JPanel panelTabel;
    public javax.swing.JTable table2;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("bread.png")));
    }
}
